version: "3"
services:
  web:
    build: .
    ports:
      - "5000:80"
    environment:
      - MSSQL_CONNECTION_STRING=Server=mssql;Database=EduJournal;User=sa;Password=Password123;
    links:
      - mssql
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=true
      - SA_PASSWORD=Password123
